In [1]:
import warnings
import numpy as np
import pandas as pd
from KNN import KNN
from sklearn.neighbors import KNeighborsClassifier
from sklearn.model_selection import train_test_split
from sklearn.metrics import confusion_matrix, accuracy_score

In [2]:
warnings.filterwarnings("ignore")

In [3]:
df = pd.read_csv('Iris.csv')

In [4]:
X = df.drop(columns=["Id", "Species"])

In [5]:
y = df[['Species']].astype("category")

In [6]:
X_train, X_test, y_train, y_test = train_test_split(
    X, y, test_size=0.20, random_state=1, stratify=y
)

In [7]:
p: int = 2
k: int = 11

In [8]:
knn = KNN(n_neighbors=k, minkowski_p=p)

In [9]:
knn.fit(X=X_train, y=y_train)

In [10]:
y_pred = knn.predict(X=X_test)

In [11]:
knn_raw_confusion_matrix: int = confusion_matrix(y_test, y_pred)
knn_raw_accuracy: int = accuracy_score(y_test, y_pred).mean() * 100

In [12]:
knn = KNeighborsClassifier(n_neighbors=k, p=p)

In [13]:
knn.fit(X_train, y_train);

In [14]:
y_pred = knn.predict(X_test)

In [15]:
knn_confusion_matrix: int = confusion_matrix(y_test, y_pred)
knn_accuracy: int = accuracy_score(y_test, y_pred).mean() * 100

In [16]:
print(knn_raw_confusion_matrix)
print(knn_raw_accuracy)

[[10  0  0]
 [ 0 10  0]
 [ 0  1  9]]
96.66666666666667


In [17]:
print(knn_confusion_matrix)
print(knn_accuracy)

[[10  0  0]
 [ 0 10  0]
 [ 0  1  9]]
96.66666666666667
